<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar"
        style="background-color: rebeccapurple">
    <a class="navbar-brand mr-0 mr-md-2" href="/" aria-label="Bootstrap">
        Framework web app sceleton
    </a>
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        <li class="nav-item">
            <a class="nav-link p-2" href="/personal">
                Personal
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link p-2" href="/blog/">
                Blog
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link p-2" href="/auth">
                Logout
            </a>
        </li>
    </ul>
</header>