<?php

namespace tests\framework\http;

use PhpAcadem\domain\User\command\UserAddCommand;
use PhpAcadem\domain\User\UserInterface;
use PhpAcadem\domain\User\UserServiceInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Command\Command;

class UserAddCommandTest extends TestCase
{
    protected $userService;
    protected $randomPassword;
    protected $wrongLogin;

    public function testInterface(): void
    {
        $this->assertInstanceOf(Command::class, new UserAddCommand($this->userService));
    }

    public function testConfigure(): void
    {
        $userAddCommand = new UserAddCommand($this->userService);

        $this->assertEquals(UserAddCommand::COMMAND_NAME, $userAddCommand->getName());

    }

    public function testExecuteEmpty(): void
    {
        $userAddCommand = new UserAddCommand($this->userService);

        $input = $this->createMock(\Symfony\Component\Console\Input\InputInterface::class);
        $output = $this->createMock(\Symfony\Component\Console\Output\OutputInterface::class);

        $result = self::callMethod($userAddCommand, 'execute', [$input, $output]);

        $this->assertEquals(UserAddCommand::COMMAND_ERROR_PARAMS, $result);
    }

    public static function callMethod($obj, $name, array $args = [])
    {
        $class = new \ReflectionClass($obj);
        $method = $class->getMethod($name);
        $method->setAccessible(true);
        return $method->invokeArgs($obj, $args);
    }

    public function testExecuteSuccess(): void
    {
        $userAddCommand = new UserAddCommand($this->userService);

        $input = $this->createMock(\Symfony\Component\Console\Input\InputInterface::class);
        $input->expects($this->any())
            ->method('getOption')
            ->will($this->returnCallback(function ($optionName) {
                if ($optionName == 'admin') {
                    return false;
                }
                return $optionName;
            }));
        $output = $this->createMock(\Symfony\Component\Console\Output\OutputInterface::class);

        $result = self::callMethod($userAddCommand, 'execute', [$input, $output]);

        $this->assertNull($result);
    }

    public function testExecuteAdminSuccess(): void
    {
        $userAddCommand = new UserAddCommand($this->userService);

        $input = $this->createMock(\Symfony\Component\Console\Input\InputInterface::class);
        $input->expects($this->any())
            ->method('getOption')
            ->will($this->returnCallback(function ($optionName) {
                if ($optionName == 'admin') {
                    return true;
                }
                return $optionName;
            }));
        $output = $this->createMock(\Symfony\Component\Console\Output\OutputInterface::class);

        $result = self::callMethod($userAddCommand, 'execute', [$input, $output]);

        $this->assertNull($result);
    }

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userService = $this->getUserService();
    }

    protected function getUserService()
    {
        $userService = $this->createMock(
            UserServiceInterface::class
        );
        $userService->expects($this->any())
            ->method('create')
            ->will($this->returnCallback(function ($args) {
                $user = $this->createMock(UserInterface::class);
                return $user;
            }));

        $userService->expects($this->any())
            ->method('create')
            ->will($this->returnCallback(function ($args) {
                $user = $this->createMock(UserInterface::class);
                return $user;
            }));


        return $userService;
    }
}