<?php

use app\route\RouteMap;

/**
 * @var \PhpAcadem\framework\view\Template $this
 * @var \PhpAcadem\domain\Content\Section[] $sections
 */
$this->layout('admin', ['title' => 'Блог']);

?>

<h1>Разделы</h1>
<p class="bd-lead">
    <a href="<?= $this->url(RouteMap::CONTENT_ADMIN_SECTION_NEW) ?>" class="btn btn-outline-primary" role="button">Новый
        раздел</a>
</p>

<td><a href=""></a></td>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Статьи</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($sections as $section) { ?>

        <tr>
            <th scope="row"><?= $section->getId() ?></th>
            <td>
                <a href="<?= $this->url(RouteMap::CONTENT_ADMIN_SECTION_EDIT, ['id' => $section->getId()]) ?>"><?= $section->getTitle() ?></a>
            </td>
            <td>
                <a href="<?= $this->url(RouteMap::CONTENT_ADMIN_ARTICLE_INDEX, ['id' => $section->getId()]) ?>">Статьи</a>
            </td>
        </tr>

    <?php } ?>
    </tbody>
</table>

