<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar"
        style="background-color: gray">
    <a class="navbar-brand mr-0 mr-md-2" href="/" aria-label="Bootstrap">
        ИС "Веб-программирование"
    </a>
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        <li class="nav-item">
            <a class="nav-link p-2 btn btn-outline-success" href="/">
                Сайт
            </a>
        </li>
        <li class="nav-item">

            <a class="nav-link p-2" href="<?= $this->url(\app\route\RouteMap::CONTENT_ADMIN_PAGE_INDEX) ?>">
                Страницы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link p-2" href="<?= $this->url(\app\route\RouteMap::CONTENT_ADMIN_SECTION_INDEX) ?>">
                Статьи
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link p-2" href="<?= $this->url(\app\route\RouteMap::CONTENT_ADMIN_MENU_INDEX) ?>">
                Меню
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link p-2" href="/auth">
                Logout
            </a>
        </li>
    </ul>
</header>