<?php
/**
 * @var \PhpAcadem\framework\view\Template $this
 * @var \PhpAcadem\domain\Blog\Post $post
 * @var \PhpAcadem\domain\User\UserInterface $user
 * @var \PhpAcadem\domain\Rbac\Rbac $rbac
 */
$rbac = $this->loadExtension('rbac');

$this->layout('main', ['title' => 'Блог']);

?>


<h1><?= $post->getTitle() ?></h1>
<p><?= $post->getContent() ?></p>

<?php
$roles = $user ? $user->getRoles() : [];
if ($rbac && $rbac->isGranted($roles, 'blog.form')) {
    ?>
    <p><a href="<?= $this->url('blog.form', ['id' => $post->getId()]) ?>">Редактировать</a></p>
<?php } ?>

