<?php
/**
 * @var \PhpAcadem\framework\view\Template $this
 * @var \PhpAcadem\domain\Content\Article $article
 * @var \PhpAcadem\domain\User\UserInterface $user
 * @var \PhpAcadem\domain\Rbac\Rbac $rbac
 */
$rbac = $this->loadExtension('rbac');

$this->layout('main', ['title' => 'Блог']);

?>
<?php
$roles = $user ? $user->getRoles() : [];
if ($rbac && $rbac->isGranted($roles, \app\route\RouteMap::CONTENT_ADMIN_ARTICLE)) {
    ?>
    <p><a href="<?= $this->url(\app\route\RouteMap::CONTENT_ADMIN_ARTICLE_EDIT, ['id' => $article->getId()]) ?>">Редактировать</a>
    </p>
<?php } ?>


<h1><?= $article->getTitle() ?></h1>
<p><?= $article->getContent() ?></p>

