<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title><?= $this->e($title) ?></title>
</head>
<body>

<?= $this->insert('layout/admin/header') ?>
<div class="container-fluid">
    <div class="row flex-xl-nowrap">

        <main class="col-12 col-md-8 col-xl-9 py-md-3 pl-md-5 bd-content" role="main">
            <?= $this->section('content') ?>
        </main>
        <div class="d-none d-md-block col-xl-3 col-md-4 bd-toc">
            <ul class="section-nav">
                <li class="toc-entry toc-h2"><a href="#approach">Approach</a></li>
                <li class="toc-entry toc-h2"><a href="#page-defaults">Page defaults</a></li>
                <li class="toc-entry toc-h2"><a href="#native-font-stack">Native font stack</a></li>
                <li class="toc-entry toc-h2"><a href="#headings-and-paragraphs">Headings and paragraphs</a></li>
                <li class="toc-entry toc-h2"><a href="#lists">Lists</a></li>
                <li class="toc-entry toc-h2"><a href="#preformatted-text">Preformatted text</a></li>
                <li class="toc-entry toc-h2"><a href="#tables">Tables</a></li>
                <li class="toc-entry toc-h2"><a href="#forms">Forms</a></li>
                <li class="toc-entry toc-h2"><a href="#misc-elements">Misc elements</a>
                    <ul>
                        <li class="toc-entry toc-h3"><a href="#address">Address</a></li>
                        <li class="toc-entry toc-h3"><a href="#blockquote">Blockquote</a></li>
                        <li class="toc-entry toc-h3"><a href="#inline-elements">Inline elements</a></li>
                        <li class="toc-entry toc-h3"><a href="#summary">Summary</a></li>
                    </ul>
                </li>
                <li class="toc-entry toc-h2"><a href="#html5-hidden-attribute">HTML5 [hidden] attribute</a></li>
            </ul>
        </div>
    </div>

</div>
</body>
</html>