<?php

use app\route\RouteMap;

/**
 * @var \PhpAcadem\framework\view\Template $this
 * @var \PhpAcadem\domain\Content\Article[] $articles
 * @var \PhpAcadem\domain\Content\Section $section
 */
$this->layout('admin', ['title' => 'Блог']);

?>

<h1>Статьи</h1>

<p class="bd-lead">
    <a href="<?= $this->url(RouteMap::CONTENT_ADMIN_ARTICLE_NEW, ['section_id' => $section->getId()]) ?>"
       class="btn btn-outline-primary" role="button">Новая статья</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Название</th>
        <th scope="col">Статус</th>
        <th scope="col">Создана</th>
        <th scope="col">Обновлена</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($articles as $article) { ?>

        <tr>
            <th scope="row"><?= $article->getId() ?></th>
            <td>
                <a href="<?= $this->url(RouteMap::CONTENT_ADMIN_ARTICLE_EDIT, ['id' => $article->getId()]) ?>"><?= $article->getTitle() ?></a>
            </td>
            <td>
                <?= $article->getStatusText() ?>
            </td>
            <td>
                <?= $article->getCreatedAt() ?>
            </td>
            <td>
                <?= $article->getUpdatedAt() ?>
            </td>
        </tr>

    <?php } ?>
    </tbody>
</table>

